#springdoc-openapi配置项
springdoc:
  swagger-ui:
    path: /swagger-ui # swagger-ui访问路径
    tags-sorter: alpha # 标签排序
  api-docs:
    path: /v3/api-docs #swagger后端请求地址
    enabled: true #是否开启文档功能
  group-configs: #分组配置
    - group: "default" # 分组名称
      paths-to-match: '/**' # 匹配路径
      packages-to-scan: com.mall #配置要扫描包的路径，一般配置到启动类即可
#knife4j配置
knife4j:
  #是否开启增强
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否认证登录
  basic:
    enable: true
    username: admin
    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
server:
  port: 1443
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zygcs_mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启sql打印
  mapper-locations: classpath:mapper/*.xml
  #全局id配置方法（使用雪花算法）
  global-config:
    db-config:
      id-type: assign_id
