# Generated by Django 5.2.1 on 2025-06-01 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tool_categories/', verbose_name='分类图标')),
            ],
            options={
                'verbose_name': '工具分类',
                'verbose_name_plural': '工具分类',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=50, verbose_name='工具名称')),
                ('link_type', models.CharField(choices=[('miniprogram', '小程序'), ('page', '本小程序页面')], max_length=20, verbose_name='链接类型')),
                ('link_target', models.CharField(max_length=200, verbose_name='链接目标')),
                ('icon', models.ImageField(upload_to='tools/', verbose_name='工具图标')),
                ('description', models.TextField(blank=True, verbose_name='工具描述')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.toolcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'ordering': ['category', 'name'],
            },
        ),
    ]
