# Generated by Django 5.2.1 on 2025-06-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='工具图标名称'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分类图标名称'),
        ),
    ]
