spring:
  application:
    name: simple-mall
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple_mall
    username: root
    password: 123456
server:
  port: 8083

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    # db-config:
    #   logic-delete-field: deleted
    #   logic-delete-value: 1
    #   logic-not-delete-value: 0
    banner: false