# Generated by Django 5.2.1 on 2025-06-01 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '代码片段分类',
                'verbose_name_plural': '代码片段分类',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('title', models.CharField(max_length=100, verbose_name='代码片段标题')),
                ('description', models.TextField(verbose_name='代码片段描述')),
                ('code', models.TextField(verbose_name='代码片段')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.snippetcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '代码片段',
                'verbose_name_plural': '代码片段',
            },
        ),
    ]
